techpack: audio: Fix compilation error for non-16061 OPPO targets
Update ifdef for mbhc variable to include 16061 only, as only it
requires these changes.

Fixes:
kernel/oppo/msm8937/techpack/audio/asoc/codecs/sdm660_cdc/msm-analog-cdc.c:2957:19: error: unused variable 'mbhc' [-Werror,-Wunused-variable]
        struct wcd_mbhc *mbhc = &sdm660_cdc->mbhc;
                         ^

Change-Id: Iadf3f43533526114cdf8f55e036288bc6961c793
Signed-off-by: Ricky Cheung <rcheung844@gmail.com>